//! Decode a base62 string
//! Performs error handling and returns a string
//! Call base62_decoder.crack to use. It returns option<String> and check with
//! `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use crate::decoders::crack_results::CrackResult;
use crate::decoders::interface::Crack;
use crate::decoders::interface::Decoder;

use log::{debug, info, trace};

/// The Base62 decoder, call:
/// `let base62_decoder = Decoder::<Base62Decoder>::new()` to create a new instance
/// And then call:
/// `result = base62_decoder.crack(input)` to decode a base62 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base62_decoder::{Base62Decoder};
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base62 = Decoder::<Base62Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base62.crack("7Dq", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "lv");
/// ```
pub struct Base62Decoder;

impl Crack for Decoder<Base62Decoder> {
    fn new() -> Decoder<Base62Decoder> {
        Decoder {
            name: "Base62",
            description: "Base62 is a binary-to-text encoding scheme that represents binary data in an ASCII string format using the characters 0-9, A-Z, and a-z.",
            link: "https://en.wikipedia.org/wiki/Base62",
            tags: vec!["base62", "base", "decoder", "classic"],
            popularity: 0.7,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an Option<string> if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base62 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());
        let decoded_text = decode_base62_no_error_handling(text);

        if decoded_text.is_none() {
            debug!("Failed to decode base62 because decode_base62_no_error_handling returned None");
            return results;
        }

        let decoded_text = decoded_text.unwrap();
        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode base62 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// helper function for base62 decoding
fn decode_base62_no_error_handling(text: &str) -> Option<String> {
    // Basic validation
    if text.is_empty() {
        return None;
    }

    // Check characters first to avoid unnecessary work
    if text.chars().any(|c| !c.is_alphanumeric()) {
        return None;
    }

    // Use base-x crate
    // GMP alphabet: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
    let alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

    match base_x::decode(alphabet, text) {
        Ok(bytes) => {
             // Convert bytes to string
             match String::from_utf8(bytes) {
                 Ok(s) => Some(s),
                 Err(_) => None,
             }
        },
        Err(_) => None,
    }
}

#[cfg(test)]
mod tests {
    use super::Base62Decoder;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn successful_decoding_1() {
        let base62_decoder = Decoder::<Base62Decoder>::new();
        // "7Dq" -> "lv" using GMP alphabet 0-9A-Za-z.
        let result = base62_decoder.crack("7Dq", &get_athena_checker());
        assert_eq!(result.unencrypted_text.unwrap()[0], "lv");
    }

    #[test]
    fn successful_decoding_numbers() {
         let base62_decoder = Decoder::<Base62Decoder>::new();
         // "13" -> "A".
         let result = base62_decoder.crack("13", &get_athena_checker());
         assert_eq!(result.unencrypted_text.unwrap()[0], "A");
    }

    #[test]
    fn base62_decode_empty_string() {
        let base62_decoder = Decoder::<Base62Decoder>::new();
        let result = base62_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn base62_decode_invalid_chars() {
        let base62_decoder = Decoder::<Base62Decoder>::new();
        let result = base62_decoder
            .crack("Hello!", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn base62_handle_panic_if_emoji() {
        let base62_decoder = Decoder::<Base62Decoder>::new();
        let result = base62_decoder
            .crack("😂", &get_athena_checker())
            .unencrypted_text;
        assert!(
            result.is_none(),
            "Decode_base62 should return None for emoji input"
        );
    }
}
