# cargo-deny is really only ever intended to run on the "normal" tier-1 targets
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"
ignore = [
    # ansi_term is unmaintained, but it does exactly what it needs to and no more
    # so no reason to change just for the sake of it
    "RUSTSEC-2021-0139",
    # atty is used in criterion, ignoring it until they update
    "RUSTSEC-2021-0145",
    # time is used in cargo-nextest, ignoring it until they update
    "RUSTSEC-2020-0071",
    # rmp-serde is used in cargo-nextest, ignoring it until they update
    "RUSTSEC-2022-0092",
]


[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = ["Apache-2.0", "Apache-2.0 WITH LLVM-exception", "MIT", "BSD-3-Clause", "OpenSSL", "MPL-2.0", "ISC", "CC0-1.0"]

exceptions = [
    { allow = [
        "Zlib",
    ], name = "tinyvec" },
    { allow = [
        "Apache-2.0",
        "BSD-2-Clause",
    ], name = "crossbeam-queue" },
    { allow = [
        "Unicode-DFS-2016",
    ], name = "unicode-ident" },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]
[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
