name: 'Handle stale PRs'
on:
    schedule:
        - cron: '30 7 * * 1-5'

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v4
              with:
                  only: pulls
                  stale-pr-message: "This PR hasn't seen activity in 2 weeks! Should it be merged, closed, or worked on further? If you want to keep it open, post a comment or remove the `stale` label – otherwise this will be closed in another week."
                  close-pr-message: 'This PR was closed due to 1 month of inactivity. Feel free to reopen it if still relevant.'
                  days-before-pr-stale: 14
                  days-before-pr-close: 30
                  stale-issue-label: stale
                  stale-pr-label: stale